### ISSUE TITLE
Astolfo image falls off screen on 1440p monitor

### ISSUE THREAD

**Issue by AlekEagle** [ArtieFuzzz/astolfo.cafe#24]
![Image of issue](https://stackowoflow.com/u8QGGNzEkX.png)

**Comment by ArtieFuzzz** [comment]
Thanks for bringing this up! I've never caught this with my monitor, I'm doing a redesign of the site making it much more minimalistic (and that removes the Astolfo image with it)

Apologies for the long response.

**Comment by ArtieFuzzz** [comment]
Now that the rewrite replaced the old site, this won't be a problem
